version: "3.9"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    command: >
      mysqld
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306

  migrator:
    image: flyway/flyway:latest
    entrypoint: ./migrate_with_delay.sh 10
    command: >
      migrate
      -user=docker
      -password=docker
      -url=jdbc:mysql://db/test_db
      -locations=filesystem:./sql
    volumes:
      - ./migrate/sql:/flyway/sql:ro
      - ./migrate/migrate_with_delay.sh:/flyway/migrate_with_delay.sh
    depends_on:
      - db
    restart: on-failure:3
